version: '3'

services:
   db:
     image: mysql:5.7
     restart: always
     ports:
      - "3306:3306"
     volumes: 
      - "./volumes/db:/var/lib/mysql" 
     environment:
       MYSQL_ROOT_PASSWORD: nodejs
       MYSQL_DATABASE: nodejs
       MYSQL_USER: nodejs
       MYSQL_PASSWORD: nodejs
     networks:
       internal:
        ipv4_address: 172.16.11.5  

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.16.11.0/24     